[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd backend && npm install --production=false']

[phases.build]
cmds = ['echo "Backend no requiere build"']

[start]
cmd = 'cd backend && node server.js'
